### ISSUE TITLE
Could not play video

### ISSUE THREAD

**Issue by elyonsaber** [helengray/XiFan#1]
试了一下，发现点击视频后，视频并没有开始播放，始终黑屏。log大概是下面这样的。
![react-native-videoview](https://cloud.githubusercontent.com/assets/15250710/19435309/7b01cc16-949c-11e6-90a3-ce0645e996c5.png)
看了下，视频源是可以正常播放的。

**Comment by helengray** [comment]
项目中是使用WebView+iframe来显示视频区域的，可以只使用WebView来显示该视频网站 @elyonsaber

**Comment by elyonsaber** [comment]
Thanks! 我再看一下
