### ISSUE TITLE
我想用一个全选的功能，求助

### ISSUE THREAD

**Issue by iamdurui** [helengray/XiFan#2]
我们的购物车里有一个全选功能，对于checkBox目前我看见check这个方法，但是不知道该怎么去写？希望给个方法，谢谢了啊

**Comment by helengray** [comment]
@iamdurui 已经实现全选功能了，具体你可以看下观看历史这块

对于checkbox全选功能，你可能遇到的疑惑可以看下我写的这篇文章，可能可以帮到你
http://blog.csdn.net/it_talk/article/details/53187074

**Comment by iamdurui** [comment]
@helengray 谢谢啊，我看见了这个博客了，我以为是用id控制全选呢。。
